@baseUrl = http://localhost:8000

GET {{baseUrl}} HTTP/1.1

###
POST {{baseUrl}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&name=Ansar
&age=23
&address=Bakti Street
&phone_number=93246382

###

PATCH {{baseUrl}}/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&address=Bukit Street
&phone_number=3245436

###

PUT {{baseUrl}}/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&name=Udin
&age=24
&address=Bodi Street
&phone_number=24545436

###

DELETE {{baseUrl}}/1 HTTP/1.1